tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
# tap "mongodb/brew"
tap "warrensbox/tap"
# tap "norwoodj/tap"
# tap "instrumenta/instrumenta"
# tap "knative-sandbox/kn-plugins"
# tap "dagger/tap"
# tap "derailed/k9s"
# tap "stripe/stripe-cli"
# tap "common-fate/granted"
# tap "sigstore/tap"
# tap "weaveworks/tap"

# Development & Power Tools
brew "git"
brew "bash"
brew "zsh"
brew "bash-completion"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zsh-completions"
# brew "wget"
# brew "coreutils"
brew 'diff-so-fancy'
brew "fzf"
# brew "gawk"
# brew "jq"
brew "watch"
# brew "telnet"
# brew "tree"
# brew "go"
# brew "python3"
# brew "gcc"
# brew "yarn"
# brew "gradle"
# brew "maven"
# brew "gh"
# brew "bfg"
# brew "serverless"
# brew "terraform"
brew "warrensbox/tap/tfswitch"
brew "awscli"
# cask "google-cloud-sdk"
# brew "mongodb/brew/mongodb-community"
# brew "postgresql@14"
# brew "redis"
# brew "firebase-cli"
brew "lsd"
brew "pass"
# brew "imagemagick"
# brew "git-xargs"
# brew "nmap"
# brew "org-stats"
# brew "k6"
# brew "stripe"
# brew "argo"
# brew "argocd"
# brew "pre-commit"
# brew "tflint"
# brew "tfsec"
# brew "terraform-docs"
# brew "terragrunt"
# brew "granted"
# brew "deno"

# Commit signing
brew 'pinentry-mac'
brew 'gnupg'
# cask 'keybase'
# brew 'gitsign'

# Containers
brew "kubernetes-cli"
brew "kubectx"
# brew "kubeval"
brew "helm"
# brew "norwoodj/tap/helm-docs"
# brew "minikube"
brew "kind"
cask "docker"
# brew "kn"
# brew "knative-sandbox/kn-plugins/quickstart"
# brew "opa"
# brew "dagger/tap/dagger"
# brew "operator-sdk"
# brew "derailed/k9s/k9s"
# cask "lens"
# brew "weaveworks/tap/eksctl"

# VMs
# brew "lima"
# cask "virtualbox"
# cask "vagrant"
# cask "vagrant-manager"

# Development
cask "visual-studio-code"
# cask "insomnia"

# Tools
cask "authy"
# cask "fig"

# Desktop Software
cask "iterm2"
# cask "zoom"
cask "slack"
cask "spotify"
# cask "google-chrome"
cask "firefox"
cask "telegram"
# cask "discord"
# cask "notion"
cask "obsidian"
cask "raycast"
# cask "sonic-pi"
# cask "steam"
